# docs: https://pre-commit.com
default_install_hook_types: [post-merge, post-checkout, post-rewrite]
repos:
  - repo: local
    hooks:
      - id: generate_localizations
        name: "Generate localization swift file"
        entry: python localizations.py Support/en.lproj/Localizable.strings generate
        language: python
        always_run: true
        stages: [post-checkout, post-merge, post-rewrite]
      - id: xcodegen
        name: Generate project files for Xcode
        description: "Generate project file for Xcode"
        entry: xcodegen
        language: system
        always_run: true
        stages: [post-checkout, post-merge, post-rewrite]
      - id: spm_dependencies
        name: Resolve SPM dependencies
        description: "Resolve SPM dependencies"
        entry: xcodebuild -resolvePackageDependencies
        language: system
        always_run: true
        stages: [post-checkout, post-merge, post-rewrite]
